# Generated by scripts/bootstrap-terraform-remote-state.sh — edit only if you change the storage account.
resource_group_name  = "rg-terraform-state"
storage_account_name = "sttfstatef9d0329c"
container_name       = "tfstate"
